### PR TITLE
feat: Add Premier Tennis

### PR DESCRIPTION
**Pull request by nickevansuk**
## Publishing Checklist

I confirm the following:

- [x] My open data feeds conform to one of the permissable combinations specified in https://developer.openactive.io/publishing-data/data-feeds/types-of-feed
- [x] My open data feeds all pass the OpenActive Validator's model validation (https://validator.openactive.io/)
- [x] My open data feeds all pass the OpenActive Validator's RPDE feed validation (https://validator.openactive.io/rpde)
- [x] My open data feeds include activity list references as specified in https://developer.openactive.io/publishing-data/activity-list-references
- [x] My dataset site(s) each reference a GitHub Issues Board

## Maintenance Checklist

Our organisation is committed to (on behalf of @drinkynet):

- [x] Resolving issues that are raised on the GitHub Issues Board(s)
- [x] Ensuring activity providers are aware of the OpenActive opportunity on an ongoing basis

### CODE REVIEW

**Comment by nickevansuk** [comment]
@drinkynet CI is failing on the feed due to some gaps in the data (see [validation-results.zip](https://github.com/openactive/data-catalogs/files/11043532/validation-results.zip))

Mostly seems to be missing addresses, but there's also a couple of missing prices

**Comment by drinkynet** [comment]
I spotted that, its failing on a single product because it's location's address is missing in the booking system. The product in question shouldn't be published to the OA feed anyway as it's an internal thing. Will have a look and see what's up with it.

**Comment by drinkynet** [comment]
Ok looks like a couple of venues have a missing address

**Comment by drinkynet** [comment]
How to you trigger a re-check of the feeds?

**Comment by nickevansuk** [comment]
Usually an empty commit to the branch - except it's my branch in this case... will trigger

**Comment by drinkynet** [comment]
lol introduced a bug, dataset site is valid according to the [validator](https://validator.openactive.io/?url=https%3A%2F%2Fapi.premiertennis.co.uk%2Fopenactive&version=2.x&validationMode=DatasetSite) now

**Comment by nickevansuk** [comment]
Just to say you can run this yourself locally rather than relying on a rerun of CI here.

Might be quicker?

https://developer.openactive.io/publishing-data/data-feeds/testing-feeds#openactive-test-suite

**Comment by drinkynet** [comment]
Yea cunning plan, doing it via test suite now ;)

**Comment by nickevansuk** [comment]
Note that validation failed in CI due to 14 occurrences of "Required property addressRegion is missing from PostalAddress".

Given https://github.com/openactive/modelling-opportunity-data/issues/209, this is likely reasonable.

**Pull request merged**
